### ISSUE TITLE
feature request: bigger font sizes

### ISSUE THREAD

**Issue by squarology** [sboesebeck/ErgodoxLayoutGenerator#6]
I'm not sure if this is the right place to put this so apologies if it's not.

Would  it be possible to increase the font sizes? They're quite small and my eyes get tired when working with ELG.

**Comment by sboesebeck** [comment]
Hi,

sure, it is the right place… for now at least.

The font sizes of the UI elements are determined by Java - I did not change them. The font size for the legend and the description of the keys is so small, as I need to put a lot of text there sometimes. I was thinking maybe to increase the font size with the window size in a later version.

or, automatically reduce the font size when the text gets too long…

not sure what would be best - probably a mixture of both… what do you think?

Am 27. Mai 2016 um 22:19:38, squarology (notifications@github.com) schrieb:

I'm not sure if this is the right place to put this so apologies if it's not.

Would it be possible to increase the font sizes? They're quite small and my eyes get tired when working with ELG.

**Comment by squarology** [comment]
I think reducing the font size as things get bigger makes sense because most keys won't have much text in them so it makes sense to favor the majority.

Also, when you select a key the key text appears at the bottom so it seems like you need only a few characters to be shown on the keys to understand what the key (esecially as it's color coded).

**Comment by sboesebeck** [comment]
yes and no. The text on the bottom can be quite long, when it comes to macros and such things.

The other thing is, that on the legend pngs created, the description text is not shown - so you need to have your key at least most of it there.

Thanks for the feedback, will think of something.

Am 27. Mai 2016 um 22:35:05, squarology (notifications@github.com) schrieb:

I think reducing the font size as things get bigger makes sense because most keys won't have much text in them so it makes sense to favor the majority.

Also, when you select a key the key text appears at the bottom so it seems like you need only a few characters to be shown on the keys to understand what the key (esecially as it's color coded).

**Comment by sboesebeck** [comment]
Just added a Pre-Release testing this feature... looks ok... could you have a look at it and tell me, if it suits your needs?

**Comment by sboesebeck** [comment]
I'll close the issue for now, as we can discuss the fine tuning here...

**Comment by squarology** [comment]
super nice!
